import { Inject, Injectable, HttpService } from '@nestjs/common';
import { GithubData, HookParse, Webhooks as GithubWebHooks } from '../interfaces';
import { CONFIG_PROIVDE, config } from '../config';
import { Template } from '../decorators';

@Injectable()
export class GitHubHookService implements HookParse {
  constructor(
    @Inject(CONFIG_PROIVDE) private readonly config,
    private readonly httpService: HttpService,
    ) {}

  @Template(config.template.github.issue)
  async issues(eventData: GithubWebHooks.WebhookPayloadIssues) {
    return eventData;

    // IssueAction
    // opened, edited, deleted, transferred, pinned, unpinned,
    // closed, reopened, assigned, unassigned, labeled, unlabeled,
    // milestoned, demilestoned, locked, or unlocked.

    // {
    //   "action": "edited",
    //     "issue": {
    //   "url": "https://api.github.com/repos/xihuanhh/test/issues/2",
    //       "repository_url": "https://api.github.com/repos/xihuanhh/test",
    //       "labels_url": "https://api.github.com/repos/xihuanhh/test/issues/2/labels{/name}",
    //       "comments_url": "https://api.github.com/repos/xihuanhh/test/issues/2/comments",
    //       "events_url": "https://api.github.com/repos/xihuanhh/test/issues/2/events",
    //       "html_url": "https://github.com/xihuanhh/test/issues/2",
    //       "id": 631354156,
    //       "node_id": "MDU6SXNzdWU2MzEzNTQxNTY=",
    //       "number": 2,
    //       "title": "test 23434",
    //       "user": {
    //     "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //   },
    //   "labels": [
    //
    //   ],
    //       "state": "open",
    //       "locked": false,
    //       "assignee": null,
    //       "assignees": [
    //
    //   ],
    //       "milestone": null,
    //       "comments": 0,
    //       "created_at": "2020-06-05T06:46:35Z",
    //       "updated_at": "2020-06-05T06:57:12Z",
    //       "closed_at": null,
    //       "author_association": "OWNER",
    //       "body": "this is test 2"
    // },
    //   "changes": {
    //   "title": {
    //     "from": "test 2"
    //   }
    // },
    //   "repository": {
    //   "id": 35196149,
    //       "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //       "name": "test",
    //       "full_name": "xihuanhh/test",
    //       "private": false,
    //       "owner": {
    //     "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //   },
    //   "html_url": "https://github.com/xihuanhh/test",
    //       "description": "test repository",
    //       "fork": false,
    //       "url": "https://api.github.com/repos/xihuanhh/test",
    //       "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //       "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //       "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //       "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //       "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //       "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //       "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //       "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //       "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //       "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //       "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //       "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //       "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //       "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //       "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //       "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //       "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //       "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //       "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //       "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //       "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //       "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //       "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //       "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //       "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //       "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //       "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //       "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //       "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //       "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //       "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //       "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //       "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //       "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //       "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //       "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //       "created_at": "2015-05-07T03:14:32Z",
    //       "updated_at": "2020-06-04T06:37:33Z",
    //       "pushed_at": "2020-06-04T06:37:31Z",
    //       "git_url": "git://github.com/xihuanhh/test.git",
    //       "ssh_url": "git@github.com:xihuanhh/test.git",
    //       "clone_url": "https://github.com/xihuanhh/test.git",
    //       "svn_url": "https://github.com/xihuanhh/test",
    //       "homepage": null,
    //       "size": 0,
    //       "stargazers_count": 1,
    //       "watchers_count": 1,
    //       "language": null,
    //       "has_issues": true,
    //       "has_projects": true,
    //       "has_downloads": true,
    //       "has_wiki": true,
    //       "has_pages": true,
    //       "forks_count": 0,
    //       "mirror_url": null,
    //       "archived": false,
    //       "disabled": false,
    //       "open_issues_count": 2,
    //       "license": null,
    //       "forks": 0,
    //       "open_issues": 2,
    //       "watchers": 1,
    //       "default_branch": "master"
    // },
    //   "sender": {
    //   "login": "xihuanhh",
    //       "id": 7556082,
    //       "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //       "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/xihuanhh",
    //       "html_url": "https://github.com/xihuanhh",
    //       "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //       "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //       "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //       "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //       "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //       "type": "User",
    //       "site_admin": false
    // }
    // }

    // const { action, issue, repository, sender } = eventData;
    // return {
    //   title: issue.title,
    //   content: issue.body,
    //   url: issue.html_url,
    //   repository: repository.full_name,
    //   action,
    //   actionLogin: sender.type + ' : ' + sender.login,
    // };
  }

  @Template(config.template.github.issueComment)
  async issue_comment(eventData: GithubWebHooks.WebhookPayloadIssueComment) {
    // IssueCommentAction
    // created, edited, or deleted.

    // {
    //   "action": "created",
    //     "issue": {
    //   "url": "https://api.github.com/repos/xihuanhh/test/issues/2",
    //       "repository_url": "https://api.github.com/repos/xihuanhh/test",
    //       "labels_url": "https://api.github.com/repos/xihuanhh/test/issues/2/labels{/name}",
    //       "comments_url": "https://api.github.com/repos/xihuanhh/test/issues/2/comments",
    //       "events_url": "https://api.github.com/repos/xihuanhh/test/issues/2/events",
    //       "html_url": "https://github.com/xihuanhh/test/issues/2",
    //       "id": 631354156,
    //       "node_id": "MDU6SXNzdWU2MzEzNTQxNTY=",
    //       "number": 2,
    //       "title": "test 23",
    //       "user": {
    //     "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //   },
    //   "labels": [
    //
    //   ],
    //       "state": "open",
    //       "locked": false,
    //       "assignee": null,
    //       "assignees": [
    //
    //   ],
    //       "milestone": null,
    //       "comments": 1,
    //       "created_at": "2020-06-05T06:46:35Z",
    //       "updated_at": "2020-06-05T07:17:13Z",
    //       "closed_at": null,
    //       "author_association": "OWNER",
    //       "body": "this is test 2"
    // },
    //   "comment": {
    //   "url": "https://api.github.com/repos/xihuanhh/test/issues/comments/639303920",
    //       "html_url": "https://github.com/xihuanhh/test/issues/2#issuecomment-639303920",
    //       "issue_url": "https://api.github.com/repos/xihuanhh/test/issues/2",
    //       "id": 639303920,
    //       "node_id": "MDEyOklzc3VlQ29tbWVudDYzOTMwMzkyMA==",
    //       "user": {
    //     "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //   },
    //   "created_at": "2020-06-05T07:17:13Z",
    //       "updated_at": "2020-06-05T07:17:13Z",
    //       "author_association": "OWNER",
    //       "body": "123123"
    // },
    //   "repository": {
    //   "id": 35196149,
    //       "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //       "name": "test",
    //       "full_name": "xihuanhh/test",
    //       "private": false,
    //       "owner": {
    //     "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //   },
    //   "html_url": "https://github.com/xihuanhh/test",
    //       "description": "test repository",
    //       "fork": false,
    //       "url": "https://api.github.com/repos/xihuanhh/test",
    //       "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //       "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //       "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //       "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //       "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //       "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //       "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //       "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //       "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //       "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //       "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //       "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //       "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //       "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //       "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //       "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //       "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //       "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //       "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //       "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //       "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //       "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //       "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //       "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //       "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //       "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //       "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //       "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //       "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //       "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //       "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //       "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //       "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //       "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //       "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //       "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //       "created_at": "2015-05-07T03:14:32Z",
    //       "updated_at": "2020-06-04T06:37:33Z",
    //       "pushed_at": "2020-06-04T06:37:31Z",
    //       "git_url": "git://github.com/xihuanhh/test.git",
    //       "ssh_url": "git@github.com:xihuanhh/test.git",
    //       "clone_url": "https://github.com/xihuanhh/test.git",
    //       "svn_url": "https://github.com/xihuanhh/test",
    //       "homepage": null,
    //       "size": 0,
    //       "stargazers_count": 1,
    //       "watchers_count": 1,
    //       "language": null,
    //       "has_issues": true,
    //       "has_projects": true,
    //       "has_downloads": true,
    //       "has_wiki": true,
    //       "has_pages": true,
    //       "forks_count": 0,
    //       "mirror_url": null,
    //       "archived": false,
    //       "disabled": false,
    //       "open_issues_count": 2,
    //       "license": null,
    //       "forks": 0,
    //       "open_issues": 2,
    //       "watchers": 1,
    //       "default_branch": "master"
    // },
    //   "sender": {
    //   "login": "xihuanhh",
    //       "id": 7556082,
    //       "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //       "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/xihuanhh",
    //       "html_url": "https://github.com/xihuanhh",
    //       "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //       "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //       "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //       "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //       "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //       "type": "User",
    //       "site_admin": false
    // }
    // }

    // const { action, issue, repository, comment, sender } = eventData;
    // return {
    //   title: issue.title,
    //   content: issue.body,
    //   url: issue.html_url,
    //   commentContent: comment.body,
    //   commentUrl: comment.html_url,
    //   repository: repository.full_name,
    //   action,
    //   actionLogin: sender.type + ' : ' + sender.login,
    // };
    return eventData;
  }

  @Template(config.template.github.push)
  async push(eventData: GithubWebHooks.WebhookPayloadPush) {
    //{
    //   "ref": "refs/heads/dev",
    //   "before": "0000000000000000000000000000000000000000",
    //   "after": "e3c7ce690330810e33ed2b25274f0f2a68e2efec",
    //   "repository": {
    //     "id": 35196149,
    //     "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //     "name": "test",
    //     "full_name": "xihuanhh/test",
    //     "private": false,
    //     "owner": {
    //       "name": "xihuanhh",
    //       "email": "750375641@qq.com",
    //       "login": "xihuanhh",
    //       "id": 7556082,
    //       "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //       "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/xihuanhh",
    //       "html_url": "https://github.com/xihuanhh",
    //       "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //       "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //       "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //       "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //       "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //       "type": "User",
    //       "site_admin": false
    //     },
    //     "html_url": "https://github.com/xihuanhh/test",
    //     "description": "test repository",
    //     "fork": false,
    //     "url": "https://github.com/xihuanhh/test",
    //     "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //     "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //     "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //     "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //     "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //     "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //     "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //     "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //     "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //     "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //     "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //     "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //     "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //     "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //     "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //     "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //     "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //     "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //     "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //     "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //     "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //     "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //     "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //     "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //     "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //     "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //     "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //     "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //     "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //     "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //     "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //     "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //     "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //     "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //     "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //     "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //     "created_at": 1430968472,
    //     "updated_at": "2020-06-04T06:37:33Z",
    //     "pushed_at": 1591343044,
    //     "git_url": "git://github.com/xihuanhh/test.git",
    //     "ssh_url": "git@github.com:xihuanhh/test.git",
    //     "clone_url": "https://github.com/xihuanhh/test.git",
    //     "svn_url": "https://github.com/xihuanhh/test",
    //     "homepage": null,
    //     "size": 0,
    //     "stargazers_count": 1,
    //     "watchers_count": 1,
    //     "language": null,
    //     "has_issues": true,
    //     "has_projects": true,
    //     "has_downloads": true,
    //     "has_wiki": true,
    //     "has_pages": true,
    //     "forks_count": 0,
    //     "mirror_url": null,
    //     "archived": false,
    //     "disabled": false,
    //     "open_issues_count": 2,
    //     "license": null,
    //     "forks": 0,
    //     "open_issues": 2,
    //     "watchers": 1,
    //     "default_branch": "master",
    //     "stargazers": 1,
    //     "master_branch": "master"
    //   },
    //   "pusher": {
    //     "name": "xihuanhh",
    //     "email": "750375641@qq.com"
    //   },
    //   "sender": {
    //     "login": "xihuanhh",
    //     "id": 7556082,
    //     "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //     "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //     "gravatar_id": "",
    //     "url": "https://api.github.com/users/xihuanhh",
    //     "html_url": "https://github.com/xihuanhh",
    //     "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //     "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //     "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //     "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //     "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //     "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //     "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //     "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //     "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //     "type": "User",
    //     "site_admin": false
    //   },
    //   "created": true,
    //   "deleted": false,
    //   "forced": false,
    //   "base_ref": "refs/heads/master",
    //   "compare": "https://github.com/xihuanhh/test/compare/dev",
    //   "commits": [
    //
    //   ],
    //   "head_commit": {
    //     "id": "e3c7ce690330810e33ed2b25274f0f2a68e2efec",
    //     "tree_id": "577682e72d422180cde2f2dbf55a80097a5d3120",
    //     "distinct": true,
    //     "message": "Set theme jekyll-theme-cayman",
    //     "timestamp": "2020-06-04T14:37:30+08:00",
    //     "url": "https://github.com/xihuanhh/test/commit/e3c7ce690330810e33ed2b25274f0f2a68e2efec",
    //     "author": {
    //       "name": "xihuanhh",
    //       "email": "750375641@qq.com",
    //       "username": "xihuanhh"
    //     },
    //     "committer": {
    //       "name": "xihuanhh",
    //       "email": "750375641@qq.com",
    //       "username": "xihuanhh"
    //     },
    //     "added": [
    //       "_config.yml"
    //     ],
    //     "removed": [
    //
    //     ],
    //     "modified": [
    //
    //     ]
    //   }
    // }
    return eventData;

    // const {
    //   ref,
    //   repository,
    //   sender,
    //   created,
    //   deleted,
    //   forced,
    //   compare,
    //   commits,
    // } = eventData;
    // return {
    //   name: ref,
    //   repository: repository.full_name,
    //   created,
    //   deleted,
    //   forced,
    //   compare,
    //   commits: commits
    //       .map(i => {
    //         return `commitId:${i.id}\nmessage:${i.message}\nurl:${i.url}\nauthor:${i.author.username}\ntime:${i.timestamp}`;
    //       })
    //       .join('\n\n'),
    //   actionLogin: sender.type + ' : ' + sender.login,
    // };
  }

  @Template(config.template.github.create)
  async create(eventData: GithubWebHooks.WebhookPayloadCreate) {
    //{
    //   "ref": "t1",
    //   "ref_type": "branch",
    //   "master_branch": "master",
    //   "description": "test repository",
    //   "pusher_type": "user",
    //   "repository": {
    //     "id": 35196149,
    //     "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //     "name": "test",
    //     "full_name": "xihuanhh/test",
    //     "private": false,
    //     "owner": {
    //       "login": "xihuanhh",
    //       "id": 7556082,
    //       "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //       "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/xihuanhh",
    //       "html_url": "https://github.com/xihuanhh",
    //       "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //       "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //       "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //       "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //       "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //       "type": "User",
    //       "site_admin": false
    //     },
    //     "html_url": "https://github.com/xihuanhh/test",
    //     "description": "test repository",
    //     "fork": false,
    //     "url": "https://api.github.com/repos/xihuanhh/test",
    //     "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //     "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //     "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //     "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //     "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //     "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //     "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //     "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //     "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //     "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //     "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //     "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //     "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //     "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //     "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //     "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //     "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //     "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //     "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //     "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //     "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //     "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //     "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //     "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //     "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //     "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //     "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //     "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //     "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //     "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //     "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //     "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //     "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //     "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //     "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //     "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //     "created_at": "2015-05-07T03:14:32Z",
    //     "updated_at": "2020-06-05T07:54:45Z",
    //     "pushed_at": "2020-06-08T02:42:01Z",
    //     "git_url": "git://github.com/xihuanhh/test.git",
    //     "ssh_url": "git@github.com:xihuanhh/test.git",
    //     "clone_url": "https://github.com/xihuanhh/test.git",
    //     "svn_url": "https://github.com/xihuanhh/test",
    //     "homepage": null,
    //     "size": 7,
    //     "stargazers_count": 1,
    //     "watchers_count": 1,
    //     "language": "JavaScript",
    //     "has_issues": true,
    //     "has_projects": true,
    //     "has_downloads": true,
    //     "has_wiki": true,
    //     "has_pages": true,
    //     "forks_count": 0,
    //     "mirror_url": null,
    //     "archived": false,
    //     "disabled": false,
    //     "open_issues_count": 2,
    //     "license": null,
    //     "forks": 0,
    //     "open_issues": 2,
    //     "watchers": 1,
    //     "default_branch": "master"
    //   },
    //   "sender": {
    //     "login": "xihuanhh",
    //     "id": 7556082,
    //     "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //     "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //     "gravatar_id": "",
    //     "url": "https://api.github.com/users/xihuanhh",
    //     "html_url": "https://github.com/xihuanhh",
    //     "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //     "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //     "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //     "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //     "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //     "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //     "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //     "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //     "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //     "type": "User",
    //     "site_admin": false
    //   }
    // }
    return eventData;

    // const { ref, ref_type, repository, sender } = eventData;
    // return {
    //   actionLogin: sender.type + ' : ' + sender.login,
    //   repository: repository.full_name,
    //   type: ref_type,
    //   name: ref,
    // };
  }

  @Template(config.template.github.delete)
  async delete(eventData: GithubWebHooks.WebhookPayloadDelete) {
    // {
    //   "ref": "dependabot/npm_and_yarn/morgan-1.10.0",
    //     "ref_type": "branch",
    //     "pusher_type": "user",
    //     "repository": {
    //   "id": 35196149,
    //       "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //       "name": "test",
    //       "full_name": "xihuanhh/test",
    //       "private": false,
    //       "owner": {
    //     "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //   },
    //   "html_url": "https://github.com/xihuanhh/test",
    //       "description": "test repository",
    //       "fork": false,
    //       "url": "https://api.github.com/repos/xihuanhh/test",
    //       "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //       "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //       "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //       "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //       "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //       "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //       "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //       "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //       "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //       "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //       "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //       "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //       "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //       "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //       "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //       "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //       "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //       "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //       "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //       "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //       "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //       "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //       "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //       "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //       "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //       "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //       "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //       "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //       "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //       "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //       "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //       "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //       "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //       "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //       "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //       "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //       "created_at": "2015-05-07T03:14:32Z",
    //       "updated_at": "2020-06-05T07:54:31Z",
    //       "pushed_at": "2020-06-05T07:54:36Z",
    //       "git_url": "git://github.com/xihuanhh/test.git",
    //       "ssh_url": "git@github.com:xihuanhh/test.git",
    //       "clone_url": "https://github.com/xihuanhh/test.git",
    //       "svn_url": "https://github.com/xihuanhh/test",
    //       "homepage": null,
    //       "size": 0,
    //       "stargazers_count": 1,
    //       "watchers_count": 1,
    //       "language": "JavaScript",
    //       "has_issues": true,
    //       "has_projects": true,
    //       "has_downloads": true,
    //       "has_wiki": true,
    //       "has_pages": true,
    //       "forks_count": 0,
    //       "mirror_url": null,
    //       "archived": false,
    //       "disabled": false,
    //       "open_issues_count": 3,
    //       "license": null,
    //       "forks": 0,
    //       "open_issues": 3,
    //       "watchers": 1,
    //       "default_branch": "master"
    // },
    //   "sender": {
    //   "login": "dependabot[bot]",
    //       "id": 49699333,
    //       "node_id": "MDM6Qm90NDk2OTkzMzM=",
    //       "avatar_url": "https://avatars0.githubusercontent.com/in/29110?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/dependabot%5Bbot%5D",
    //       "html_url": "https://github.com/apps/dependabot",
    //       "followers_url": "https://api.github.com/users/dependabot%5Bbot%5D/followers",
    //       "following_url": "https://api.github.com/users/dependabot%5Bbot%5D/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/dependabot%5Bbot%5D/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/dependabot%5Bbot%5D/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/dependabot%5Bbot%5D/subscriptions",
    //       "organizations_url": "https://api.github.com/users/dependabot%5Bbot%5D/orgs",
    //       "repos_url": "https://api.github.com/users/dependabot%5Bbot%5D/repos",
    //       "events_url": "https://api.github.com/users/dependabot%5Bbot%5D/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/dependabot%5Bbot%5D/received_events",
    //       "type": "Bot",
    //       "site_admin": false
    // }
    // }

    return eventData;
  }

  @Template(config.template.github.pullRequest)
  async pull_request(eventData: GithubWebHooks.WebhookPayloadPullRequest) {
    //{
    //   "action": "opened",
    //   "number": 5,
    //   "pull_request": {
    //     "url": "https://api.github.com/repos/xihuanhh/test/pulls/5",
    //     "id": 430784412,
    //     "node_id": "MDExOlB1bGxSZXF1ZXN0NDMwNzg0NDEy",
    //     "html_url": "https://github.com/xihuanhh/test/pull/5",
    //     "diff_url": "https://github.com/xihuanhh/test/pull/5.diff",
    //     "patch_url": "https://github.com/xihuanhh/test/pull/5.patch",
    //     "issue_url": "https://api.github.com/repos/xihuanhh/test/issues/5",
    //     "number": 5,
    //     "state": "open",
    //     "locked": false,
    //     "title": "Dev",
    //     "user": {
    //       "login": "xihuanhh",
    //       "id": 7556082,
    //       "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //       "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/xihuanhh",
    //       "html_url": "https://github.com/xihuanhh",
    //       "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //       "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //       "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //       "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //       "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //       "type": "User",
    //       "site_admin": false
    //     },
    //     "body": "测试pr\r\n",
    //     "created_at": "2020-06-08T06:06:21Z",
    //     "updated_at": "2020-06-08T06:06:21Z",
    //     "closed_at": null,
    //     "merged_at": null,
    //     "merge_commit_sha": null,
    //     "assignee": null,
    //     "assignees": [
    //
    //     ],
    //     "requested_reviewers": [
    //
    //     ],
    //     "requested_teams": [
    //
    //     ],
    //     "labels": [
    //
    //     ],
    //     "milestone": null,
    //     "draft": false,
    //     "commits_url": "https://api.github.com/repos/xihuanhh/test/pulls/5/commits",
    //     "review_comments_url": "https://api.github.com/repos/xihuanhh/test/pulls/5/comments",
    //     "review_comment_url": "https://api.github.com/repos/xihuanhh/test/pulls/comments{/number}",
    //     "comments_url": "https://api.github.com/repos/xihuanhh/test/issues/5/comments",
    //     "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/d65f454953f8c08e4e37ad32ef6f14e93223c916",
    //     "head": {
    //       "label": "xihuanhh:dev",
    //       "ref": "dev",
    //       "sha": "d65f454953f8c08e4e37ad32ef6f14e93223c916",
    //       "user": {
    //         "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //       },
    //       "repo": {
    //         "id": 35196149,
    //         "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //         "name": "test",
    //         "full_name": "xihuanhh/test",
    //         "private": false,
    //         "owner": {
    //           "login": "xihuanhh",
    //           "id": 7556082,
    //           "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //           "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //           "gravatar_id": "",
    //           "url": "https://api.github.com/users/xihuanhh",
    //           "html_url": "https://github.com/xihuanhh",
    //           "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //           "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //           "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //           "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //           "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //           "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //           "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //           "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //           "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //           "type": "User",
    //           "site_admin": false
    //         },
    //         "html_url": "https://github.com/xihuanhh/test",
    //         "description": "test repository",
    //         "fork": false,
    //         "url": "https://api.github.com/repos/xihuanhh/test",
    //         "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //         "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //         "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //         "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //         "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //         "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //         "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //         "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //         "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //         "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //         "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //         "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //         "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //         "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //         "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //         "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //         "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //         "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //         "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //         "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //         "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //         "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //         "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //         "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //         "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //         "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //         "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //         "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //         "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //         "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //         "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //         "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //         "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //         "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //         "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //         "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //         "created_at": "2015-05-07T03:14:32Z",
    //         "updated_at": "2020-06-05T07:54:45Z",
    //         "pushed_at": "2020-06-08T02:42:01Z",
    //         "git_url": "git://github.com/xihuanhh/test.git",
    //         "ssh_url": "git@github.com:xihuanhh/test.git",
    //         "clone_url": "https://github.com/xihuanhh/test.git",
    //         "svn_url": "https://github.com/xihuanhh/test",
    //         "homepage": null,
    //         "size": 10,
    //         "stargazers_count": 1,
    //         "watchers_count": 1,
    //         "language": "JavaScript",
    //         "has_issues": true,
    //         "has_projects": true,
    //         "has_downloads": true,
    //         "has_wiki": true,
    //         "has_pages": true,
    //         "forks_count": 0,
    //         "mirror_url": null,
    //         "archived": false,
    //         "disabled": false,
    //         "open_issues_count": 3,
    //         "license": null,
    //         "forks": 0,
    //         "open_issues": 3,
    //         "watchers": 1,
    //         "default_branch": "master"
    //       }
    //     },
    //     "base": {
    //       "label": "xihuanhh:master",
    //       "ref": "master",
    //       "sha": "5fda993d395c095e69e57625a384160ad26d26e3",
    //       "user": {
    //         "login": "xihuanhh",
    //         "id": 7556082,
    //         "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //         "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //         "gravatar_id": "",
    //         "url": "https://api.github.com/users/xihuanhh",
    //         "html_url": "https://github.com/xihuanhh",
    //         "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //         "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //         "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //         "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //         "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //         "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //         "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //         "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //         "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //         "type": "User",
    //         "site_admin": false
    //       },
    //       "repo": {
    //         "id": 35196149,
    //         "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //         "name": "test",
    //         "full_name": "xihuanhh/test",
    //         "private": false,
    //         "owner": {
    //           "login": "xihuanhh",
    //           "id": 7556082,
    //           "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //           "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //           "gravatar_id": "",
    //           "url": "https://api.github.com/users/xihuanhh",
    //           "html_url": "https://github.com/xihuanhh",
    //           "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //           "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //           "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //           "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //           "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //           "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //           "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //           "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //           "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //           "type": "User",
    //           "site_admin": false
    //         },
    //         "html_url": "https://github.com/xihuanhh/test",
    //         "description": "test repository",
    //         "fork": false,
    //         "url": "https://api.github.com/repos/xihuanhh/test",
    //         "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //         "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //         "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //         "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //         "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //         "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //         "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //         "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //         "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //         "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //         "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //         "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //         "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //         "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //         "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //         "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //         "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //         "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //         "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //         "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //         "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //         "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //         "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //         "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //         "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //         "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //         "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //         "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //         "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //         "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //         "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //         "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //         "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //         "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //         "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //         "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //         "created_at": "2015-05-07T03:14:32Z",
    //         "updated_at": "2020-06-05T07:54:45Z",
    //         "pushed_at": "2020-06-08T02:42:01Z",
    //         "git_url": "git://github.com/xihuanhh/test.git",
    //         "ssh_url": "git@github.com:xihuanhh/test.git",
    //         "clone_url": "https://github.com/xihuanhh/test.git",
    //         "svn_url": "https://github.com/xihuanhh/test",
    //         "homepage": null,
    //         "size": 10,
    //         "stargazers_count": 1,
    //         "watchers_count": 1,
    //         "language": "JavaScript",
    //         "has_issues": true,
    //         "has_projects": true,
    //         "has_downloads": true,
    //         "has_wiki": true,
    //         "has_pages": true,
    //         "forks_count": 0,
    //         "mirror_url": null,
    //         "archived": false,
    //         "disabled": false,
    //         "open_issues_count": 3,
    //         "license": null,
    //         "forks": 0,
    //         "open_issues": 3,
    //         "watchers": 1,
    //         "default_branch": "master"
    //       }
    //     },
    //     "_links": {
    //       "self": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/pulls/5"
    //       },
    //       "html": {
    //         "href": "https://github.com/xihuanhh/test/pull/5"
    //       },
    //       "issue": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/issues/5"
    //       },
    //       "comments": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/issues/5/comments"
    //       },
    //       "review_comments": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/pulls/5/comments"
    //       },
    //       "review_comment": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/pulls/comments{/number}"
    //       },
    //       "commits": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/pulls/5/commits"
    //       },
    //       "statuses": {
    //         "href": "https://api.github.com/repos/xihuanhh/test/statuses/d65f454953f8c08e4e37ad32ef6f14e93223c916"
    //       }
    //     },
    //     "author_association": "OWNER",
    //     "merged": false,
    //     "mergeable": null,
    //     "rebaseable": null,
    //     "mergeable_state": "unknown",
    //     "merged_by": null,
    //     "comments": 0,
    //     "review_comments": 0,
    //     "maintainer_can_modify": false,
    //     "commits": 3,
    //     "additions": 92,
    //     "deletions": 0,
    //     "changed_files": 1
    //   },
    //   "repository": {
    //     "id": 35196149,
    //     "node_id": "MDEwOlJlcG9zaXRvcnkzNTE5NjE0OQ==",
    //     "name": "test",
    //     "full_name": "xihuanhh/test",
    //     "private": false,
    //     "owner": {
    //       "login": "xihuanhh",
    //       "id": 7556082,
    //       "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //       "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //       "gravatar_id": "",
    //       "url": "https://api.github.com/users/xihuanhh",
    //       "html_url": "https://github.com/xihuanhh",
    //       "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //       "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //       "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //       "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //       "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //       "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //       "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //       "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //       "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //       "type": "User",
    //       "site_admin": false
    //     },
    //     "html_url": "https://github.com/xihuanhh/test",
    //     "description": "test repository",
    //     "fork": false,
    //     "url": "https://api.github.com/repos/xihuanhh/test",
    //     "forks_url": "https://api.github.com/repos/xihuanhh/test/forks",
    //     "keys_url": "https://api.github.com/repos/xihuanhh/test/keys{/key_id}",
    //     "collaborators_url": "https://api.github.com/repos/xihuanhh/test/collaborators{/collaborator}",
    //     "teams_url": "https://api.github.com/repos/xihuanhh/test/teams",
    //     "hooks_url": "https://api.github.com/repos/xihuanhh/test/hooks",
    //     "issue_events_url": "https://api.github.com/repos/xihuanhh/test/issues/events{/number}",
    //     "events_url": "https://api.github.com/repos/xihuanhh/test/events",
    //     "assignees_url": "https://api.github.com/repos/xihuanhh/test/assignees{/user}",
    //     "branches_url": "https://api.github.com/repos/xihuanhh/test/branches{/branch}",
    //     "tags_url": "https://api.github.com/repos/xihuanhh/test/tags",
    //     "blobs_url": "https://api.github.com/repos/xihuanhh/test/git/blobs{/sha}",
    //     "git_tags_url": "https://api.github.com/repos/xihuanhh/test/git/tags{/sha}",
    //     "git_refs_url": "https://api.github.com/repos/xihuanhh/test/git/refs{/sha}",
    //     "trees_url": "https://api.github.com/repos/xihuanhh/test/git/trees{/sha}",
    //     "statuses_url": "https://api.github.com/repos/xihuanhh/test/statuses/{sha}",
    //     "languages_url": "https://api.github.com/repos/xihuanhh/test/languages",
    //     "stargazers_url": "https://api.github.com/repos/xihuanhh/test/stargazers",
    //     "contributors_url": "https://api.github.com/repos/xihuanhh/test/contributors",
    //     "subscribers_url": "https://api.github.com/repos/xihuanhh/test/subscribers",
    //     "subscription_url": "https://api.github.com/repos/xihuanhh/test/subscription",
    //     "commits_url": "https://api.github.com/repos/xihuanhh/test/commits{/sha}",
    //     "git_commits_url": "https://api.github.com/repos/xihuanhh/test/git/commits{/sha}",
    //     "comments_url": "https://api.github.com/repos/xihuanhh/test/comments{/number}",
    //     "issue_comment_url": "https://api.github.com/repos/xihuanhh/test/issues/comments{/number}",
    //     "contents_url": "https://api.github.com/repos/xihuanhh/test/contents/{+path}",
    //     "compare_url": "https://api.github.com/repos/xihuanhh/test/compare/{base}...{head}",
    //     "merges_url": "https://api.github.com/repos/xihuanhh/test/merges",
    //     "archive_url": "https://api.github.com/repos/xihuanhh/test/{archive_format}{/ref}",
    //     "downloads_url": "https://api.github.com/repos/xihuanhh/test/downloads",
    //     "issues_url": "https://api.github.com/repos/xihuanhh/test/issues{/number}",
    //     "pulls_url": "https://api.github.com/repos/xihuanhh/test/pulls{/number}",
    //     "milestones_url": "https://api.github.com/repos/xihuanhh/test/milestones{/number}",
    //     "notifications_url": "https://api.github.com/repos/xihuanhh/test/notifications{?since,all,participating}",
    //     "labels_url": "https://api.github.com/repos/xihuanhh/test/labels{/name}",
    //     "releases_url": "https://api.github.com/repos/xihuanhh/test/releases{/id}",
    //     "deployments_url": "https://api.github.com/repos/xihuanhh/test/deployments",
    //     "created_at": "2015-05-07T03:14:32Z",
    //     "updated_at": "2020-06-05T07:54:45Z",
    //     "pushed_at": "2020-06-08T02:42:01Z",
    //     "git_url": "git://github.com/xihuanhh/test.git",
    //     "ssh_url": "git@github.com:xihuanhh/test.git",
    //     "clone_url": "https://github.com/xihuanhh/test.git",
    //     "svn_url": "https://github.com/xihuanhh/test",
    //     "homepage": null,
    //     "size": 10,
    //     "stargazers_count": 1,
    //     "watchers_count": 1,
    //     "language": "JavaScript",
    //     "has_issues": true,
    //     "has_projects": true,
    //     "has_downloads": true,
    //     "has_wiki": true,
    //     "has_pages": true,
    //     "forks_count": 0,
    //     "mirror_url": null,
    //     "archived": false,
    //     "disabled": false,
    //     "open_issues_count": 3,
    //     "license": null,
    //     "forks": 0,
    //     "open_issues": 3,
    //     "watchers": 1,
    //     "default_branch": "master"
    //   },
    //   "sender": {
    //     "login": "xihuanhh",
    //     "id": 7556082,
    //     "node_id": "MDQ6VXNlcjc1NTYwODI=",
    //     "avatar_url": "https://avatars1.githubusercontent.com/u/7556082?v=4",
    //     "gravatar_id": "",
    //     "url": "https://api.github.com/users/xihuanhh",
    //     "html_url": "https://github.com/xihuanhh",
    //     "followers_url": "https://api.github.com/users/xihuanhh/followers",
    //     "following_url": "https://api.github.com/users/xihuanhh/following{/other_user}",
    //     "gists_url": "https://api.github.com/users/xihuanhh/gists{/gist_id}",
    //     "starred_url": "https://api.github.com/users/xihuanhh/starred{/owner}{/repo}",
    //     "subscriptions_url": "https://api.github.com/users/xihuanhh/subscriptions",
    //     "organizations_url": "https://api.github.com/users/xihuanhh/orgs",
    //     "repos_url": "https://api.github.com/users/xihuanhh/repos",
    //     "events_url": "https://api.github.com/users/xihuanhh/events{/privacy}",
    //     "received_events_url": "https://api.github.com/users/xihuanhh/received_events",
    //     "type": "User",
    //     "site_admin": false
    //   }
    // }
    return eventData;

    // const { action, pull_request } = eventData;
    // return {
    //   action,
    //   title: pull_request.title,
    //   url: pull_request.html_url,
    //   state: pull_request.state,
    //   content: pull_request.body,
    //   actionLogin: pull_request.user.type + ' : ' + pull_request.user.login,
    //   createdAt: pull_request.created_at,
    //   updatedAt: pull_request.updated_at,
    //   closedAt: pull_request.closed_at,
    //   mergedAt: pull_request.merged_at,
    //   from:
    //       pull_request.head.user.login +
    //       ' 从仓库: ' +
    //       pull_request.head.repo.full_name +
    //       ' 发起合并, 分支:' +
    //       pull_request.head.label,
    //   to:
    //       '请求合并到 ' +
    //       pull_request.base.user.login +
    //       '的仓库 ' +
    //       pull_request.base.repo.full_name +
    //       '的分支: ' +
    //       pull_request.base.label,
    // };
  }

  async parse(data: GithubData, event: string): Promise<string> {
    this.httpService.post('https://smee.io/UxI3pIRcr01UpJ0',data)
    if (this[event]) {
      return this[event](data, event);
    }
    return '';
  }
}
