name: Docker Image CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - ".vscode/**"
    - docs
    - test
    - .env.sample
    - README.md
jobs:

  build:

    runs-on: [ubuntu-latest]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: iyjian/dev-raven:latest
